---
title: "taxa_bar"
author: "Shimin Gu"
date: "2024-08-19"
output: html_document
---

```{r}
#load packages
library(viridis)
library(dplyr)
library(rphylopic)
library(png)
library(patchwork)
library(ggplot2)

#load data
taxa_curr_bar <- read.csv("taxa_curr_bar.csv", sep =",", header =T)
taxa_ssp1_bar <- read.csv("taxa_ssp1_bar.csv", sep =",", header =T)
taxa_ssp2_bar <- read.csv("taxa_ssp2_bar.csv", sep =",", header =T)
taxa_ssp5_bar <- read.csv("taxa_ssp5_bar.csv", sep =",", header =T)
```

```{r}
for (i in 1:121){
  for (j in 1:170){
  if (taxa_curr_bar$s_Species[i]==taxa_curr_bar$Species[j] && taxa_curr_bar$Type_of_cost_merged[j]=="Damage"){taxa_curr_bar$s_Damage[i]=taxa_curr_bar$pred_cost_mean[j]}
  if (taxa_curr_bar$s_Species[i]==taxa_curr_bar$Species[j] && taxa_curr_bar$Type_of_cost_merged[j]=="Management"){taxa_curr_bar$s_manage[i]=taxa_curr_bar$pred_cost_mean[j]}
  if (taxa_curr_bar$s_Species[i]==taxa_curr_bar$Species[j] && taxa_curr_bar$Type_of_cost_merged[j]=="Mixed"){taxa_curr_bar$s_mixed[i]=taxa_curr_bar$pred_cost_mean[j]}
  if (taxa_curr_bar$s_Species[i]==taxa_curr_bar$Species[j] && taxa_curr_bar$Type_of_cost_merged[j]=="Unspecified"){taxa_curr_bar$s_unspecified[i]=taxa_curr_bar$pred_cost_mean[j]}
  }
}

for (i in 1:121){
  for (j in 1:170){
  if (taxa_ssp1_bar$s_Species[i]==taxa_ssp1_bar$Species[j] && taxa_ssp1_bar$Type_of_cost_merged[j]=="Damage"){taxa_ssp1_bar$s_Damage[i]=taxa_ssp1_bar$pred_cost_mean[j]}
  if (taxa_ssp1_bar$s_Species[i]==taxa_ssp1_bar$Species[j] && taxa_ssp1_bar$Type_of_cost_merged[j]=="Management"){taxa_ssp1_bar$s_manage[i]=taxa_ssp1_bar$pred_cost_mean[j]}
  if (taxa_ssp1_bar$s_Species[i]==taxa_ssp1_bar$Species[j] && taxa_ssp1_bar$Type_of_cost_merged[j]=="Mixed"){taxa_ssp1_bar$s_mixed[i]=taxa_ssp1_bar$pred_cost_mean[j]}
  if (taxa_ssp1_bar$s_Species[i]==taxa_ssp1_bar$Species[j] && taxa_ssp1_bar$Type_of_cost_merged[j]=="Unspecified"){taxa_ssp1_bar$s_unspecified[i]=taxa_ssp1_bar$pred_cost_mean[j]}
  }
}

for (i in 1:121){
  for (j in 1:170){
  if (taxa_ssp2_bar$s_Species[i]==taxa_ssp2_bar$Species[j] && taxa_ssp2_bar$Type_of_cost_merged[j]=="Damage"){taxa_ssp2_bar$s_Damage[i]=taxa_ssp2_bar$pred_cost_mean[j]}
  if (taxa_ssp2_bar$s_Species[i]==taxa_ssp2_bar$Species[j] && taxa_ssp2_bar$Type_of_cost_merged[j]=="Management"){taxa_ssp2_bar$s_manage[i]=taxa_ssp2_bar$pred_cost_mean[j]}
  if (taxa_ssp2_bar$s_Species[i]==taxa_ssp2_bar$Species[j] && taxa_ssp2_bar$Type_of_cost_merged[j]=="Mixed"){taxa_ssp2_bar$s_mixed[i]=taxa_ssp2_bar$pred_cost_mean[j]}
  if (taxa_ssp2_bar$s_Species[i]==taxa_ssp2_bar$Species[j] && taxa_ssp2_bar$Type_of_cost_merged[j]=="Unspecified"){taxa_ssp2_bar$s_unspecified[i]=taxa_ssp2_bar$pred_cost_mean[j]}
  }
}

for (i in 1:121){
  for (j in 1:170){
  if (taxa_ssp5_bar$s_Species[i]==taxa_ssp5_bar$Species[j] && taxa_ssp5_bar$Type_of_cost_merged[j]=="Damage"){taxa_ssp5_bar$s_Damage[i]=taxa_ssp5_bar$pred_cost_mean[j]}
  if (taxa_ssp5_bar$s_Species[i]==taxa_ssp5_bar$Species[j] && taxa_ssp5_bar$Type_of_cost_merged[j]=="Management"){taxa_ssp5_bar$s_manage[i]=taxa_ssp5_bar$pred_cost_mean[j]}
  if (taxa_ssp5_bar$s_Species[i]==taxa_ssp5_bar$Species[j] && taxa_ssp5_bar$Type_of_cost_merged[j]=="Mixed"){taxa_ssp5_bar$s_mixed[i]=taxa_ssp5_bar$pred_cost_mean[j]}
  if (taxa_ssp5_bar$s_Species[i]==taxa_ssp5_bar$Species[j] && taxa_ssp5_bar$Type_of_cost_merged[j]=="Unspecified"){taxa_ssp5_bar$s_unspecified[i]=taxa_ssp5_bar$pred_cost_mean[j]}
  }
}
```

#top ten species
```{r}
n = 10
k = 1+n
j = n*2
m = 1+n*2
p = n*3
b = 1+n*3
v = n*4
taxa_curr_bar_top10 <- taxa_curr_bar[1:n,6:10]
taxa_curr_bar_top10 <- rbind(taxa_curr_bar_top10,taxa_curr_bar_top10,taxa_curr_bar_top10,taxa_curr_bar_top10)
taxa_curr_bar_top10[k:j,2] <- taxa_curr_bar_top10[k:j,3]
taxa_curr_bar_top10[m:p,2] <- taxa_curr_bar_top10[m:p,4]
taxa_curr_bar_top10[b:v,2] <- taxa_curr_bar_top10[b:v,5]
taxa_curr_bar_top10 <- taxa_curr_bar_top10[,1:2]
colnames(taxa_curr_bar_top10) <- c("s_Species","pred_cost")
taxa_curr_bar_top10$Type_of_cost_merged <- c(rep("Damage",n),rep("Management",n),rep("Mixed",n),rep("Unspecified",n))
taxa_curr_bar_top10$group <- "current"
taxa_curr_bar_top10$num_s_Species <- c(rep(1:10,4))

taxa_ssp1_bar_top10 <- taxa_ssp1_bar[1:n,6:10]
taxa_ssp1_bar_top10 <- rbind(taxa_ssp1_bar_top10,taxa_ssp1_bar_top10,taxa_ssp1_bar_top10,taxa_ssp1_bar_top10)
taxa_ssp1_bar_top10[k:j,2] <- taxa_ssp1_bar_top10[k:j,3]
taxa_ssp1_bar_top10[m:p,2] <- taxa_ssp1_bar_top10[m:p,4]
taxa_ssp1_bar_top10[b:v,2] <- taxa_ssp1_bar_top10[b:v,5]
taxa_ssp1_bar_top10 <- taxa_ssp1_bar_top10[,1:2]
colnames(taxa_ssp1_bar_top10) <- c("s_Species","pred_cost")
taxa_ssp1_bar_top10$Type_of_cost_merged <- c(rep("Damage",n),rep("Management",n),rep("Mixed",n),rep("Unspecified",n))
taxa_ssp1_bar_top10$group <- "ssp1"
taxa_ssp1_bar_top10$num_s_Species <- c(rep(1:10,4))

taxa_ssp2_bar_top10 <- taxa_ssp2_bar[1:n,6:10]
taxa_ssp2_bar_top10 <- rbind(taxa_ssp2_bar_top10,taxa_ssp2_bar_top10,taxa_ssp2_bar_top10,taxa_ssp2_bar_top10)
taxa_ssp2_bar_top10[k:j,2] <- taxa_ssp2_bar_top10[k:j,3]
taxa_ssp2_bar_top10[m:p,2] <- taxa_ssp2_bar_top10[m:p,4]
taxa_ssp2_bar_top10[b:v,2] <- taxa_ssp2_bar_top10[b:v,5]
taxa_ssp2_bar_top10 <- taxa_ssp2_bar_top10[,1:2]
colnames(taxa_ssp2_bar_top10) <- c("s_Species","pred_cost")
taxa_ssp2_bar_top10$Type_of_cost_merged <- c(rep("Damage",n),rep("Management",n),rep("Mixed",n),rep("Unspecified",n))
taxa_ssp2_bar_top10$group <- "ssp2"
taxa_ssp2_bar_top10$num_s_Species <- c(rep(1:10,4))

taxa_ssp5_bar_top10 <- taxa_ssp5_bar[1:n,6:10]
taxa_ssp5_bar_top10 <- rbind(taxa_ssp5_bar_top10,taxa_ssp5_bar_top10,taxa_ssp5_bar_top10,taxa_ssp5_bar_top10)
taxa_ssp5_bar_top10[k:j,2] <- taxa_ssp5_bar_top10[k:j,3]
taxa_ssp5_bar_top10[m:p,2] <- taxa_ssp5_bar_top10[m:p,4]
taxa_ssp5_bar_top10[b:v,2] <- taxa_ssp5_bar_top10[b:v,5]
taxa_ssp5_bar_top10 <- taxa_ssp5_bar_top10[,1:2]
colnames(taxa_ssp5_bar_top10) <- c("s_Species","pred_cost")
taxa_ssp5_bar_top10$Type_of_cost_merged <- c(rep("Damage",n),rep("Management",n),rep("Mixed",n),rep("Unspecified",n))
taxa_ssp5_bar_top10$group <- "ssp5"
taxa_ssp5_bar_top10$num_s_Species <- c(rep(1:10,4))
```

#plotting

#------------read the "taxa_scatter.Rmd"----------------

#get animal icon
```{r}
pdf(width = 9, height = 4, file = "fig4i_top10_icon.pdf")

uuid_1 <- get_uuid(name = "Aedes aegypti");img_1 <- get_phylopic(uuid = uuid_1)
uuid_2 <- get_uuid(name = "Anthonomus grandis");img_2 <- get_phylopic(uuid = uuid_2)
uuid_3 <- get_uuid(name = "Rattus");img_3 <- get_phylopic(uuid = uuid_3)
uuid_4 <- get_uuid(name = "Coptotermes formosanus");img_4 <- get_phylopic(uuid = uuid_4)
uuid_5 <- get_uuid(name = "Bursaphelenchus xylophilus");img_5 <- get_phylopic(uuid = uuid_5)
uuid_6 <- get_uuid(name = "Autographa gamma");img_6 <- get_phylopic(uuid = uuid_6)
uuid_7 <- get_uuid(name = "Calliphoridae");img_7 <- get_phylopic(uuid = uuid_7)
uuid_8 <- get_uuid(name = "Ixodes ricinus");img_8 <- get_phylopic(uuid = uuid_8)
uuid_9 <- get_uuid(name = "Sophophora pseudoobscura");img_9 <- get_phylopic(uuid = uuid_9)
uuid_10 <- get_uuid(name = "Anoplophora");img_10 <- get_phylopic(uuid = uuid_10)

#extra for fig 5
uuid_11 <- get_uuid(name = "Sus scrofa");img_11 <- get_phylopic(uuid = uuid_11)

ysize_pic = 1.2
color_pic = "black"

sizetext <- 10
compare_list <- list(
    c("current","ssp1"),
    c("current","ssp2"),
    c("current","ssp5"))
    
ggplot(taxa_terrinv,aes(x = group,y = pred_cost_mean)) +
  geom_col(data = taxa_terrinv_bg, 
           mapping = aes(group,max_pred),
           fill = "grey85", width = 0.8, alpha = 0.15) +
  geom_col(data = taxa_terrinv_bg, 
           mapping = aes(group, min_pred),
           fill = "grey85", width = 0.8, alpha = 0.15) +
  geom_jitter(aes(color = group), size = 0.8, alpha = 0.65)+
  # geom_boxplot(aes(fill = group),alpha = 0.7)+
  scale_y_continuous(trans = 'log10', breaks = c(0,1,100,1000,10000,100000), labels = scales::comma)+
  scale_color_manual(values = c("#97979730","#FED3C2","#FD9780","#611320"))+
  theme_classic(base_size = sizetext)+
  theme(axis.ticks = element_line(colour = "black", linewidth = 0.2),
        axis.text = element_text(size = sizetext, colour = "black"),
        axis.title = element_text(size = sizetext), 
        axis.text.x = element_text(angle=30, hjust=1), legend.position = "none")+
  labs(x="Climate scenario", y="Potential economic cost (millions of US$)")+
  stat_compare_means(
    comparisons = compare_list,
    method = "wilcox.test",paired = T,
    label = "p.signif")+
  add_phylopic(x ="current", y =80000, img = img_1, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp1", y =80000, img = img_2, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp2", y =80000, img = img_3, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp5", y =80000, img = img_4, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="current", y =1000, img = img_5, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp1", y =1000, img = img_6, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp2", y =1000, img = img_7, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp5", y =1000, img = img_8, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="current", y =1, img = img_9, ysize = ysize_pic, color = color_pic)+
  add_phylopic(x ="ssp1", y =1, img = img_10, ysize = ysize_pic, color = color_pic)+
  #extra for fig 5
  add_phylopic(x ="ssp5", y =1, img = img_11, ysize = ysize_pic, color = color_pic)

dev.off()

```

```{r}
pdf(width = 10, height = 6, file = "fig4i_top10.pdf")



sizetext <- 12

ggplot()+
  geom_bar(data=taxa_curr_bar_top10,aes(x=num_s_Species,y=pred_cost,fill= Type_of_cost_merged ,color=group),stat = "identity",position = "stack",width=0.2)+
  geom_bar(data=taxa_ssp1_bar_top10,aes(x=num_s_Species+0.2,y=pred_cost,fill= Type_of_cost_merged ,color=group),stat = "identity",position = "stack",width=0.2)+
  geom_bar(data=taxa_ssp2_bar_top10,aes(x=num_s_Species+0.2+0.2,y=pred_cost,fill= Type_of_cost_merged ,color=group),stat = "identity",position = "stack",width=0.2)+
  geom_bar(data=taxa_ssp5_bar_top10,aes(x=num_s_Species+0.2+0.2+0.2,y=pred_cost,fill= Type_of_cost_merged,color=group),stat="identity",position = "stack",width=0.2)+
  
  scale_fill_manual(values = c("Damage"="#A2A4CE","Management"="#99C9E3","Mixed"="#D5D5E7","Unspecified"="#00000050"))+
  scale_color_manual(values = c("current"="white","ssp1"="white","ssp2"="white","ssp5"="white"))+


  scale_x_continuous(breaks = c(1.3,2.3,3.3,4.3,5.3,6.3,7.3,8.3,9.3,10.3),
                     labels = c("Aedes aegypti","Anthonomus grandis","Rattus rattus","Coptotermes formosanus","Bursaphelenchus mucronatus",
                                "Spodoptera frugiperda","Haematobia irritans","Rhipicephalus microplus","Stomoxys calcitrans","Anoplophora glabripennis"))+
  scale_y_continuous(limits = c(0,120000), labels = scales::comma)+
  labs(x="Taxon", y="Potential total economic cost\n(millions of US$)")+
  theme_classic(base_size = sizetext)+
  theme(axis.ticks = element_line(colour = "black", linewidth = 0.2),
        axis.text = element_text(size = sizetext, colour = "black"),
        axis.title = element_text(size = sizetext), 
        axis.text.x = element_text(angle=30, hjust=1), legend.position = "right",
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        panel.background = element_rect(fill = 'white', colour = 'white'), 
        panel.grid.minor = element_line(color = 'white'), 
        panel.grid.major = element_line(color = 'white'))
  

dev.off()

```

